### ISSUE TITLE
Can't install via Cocoapods

### ISSUE THREAD

**Issue by ecristerna** [Ssimboss/Image360#1]
For some reason, cocoapods won't let me install the files. I'm using the specified name and tag (`pod 'Image360', '~> 0.1.3'`), but it throws me the next message: `[!] Unable to find a specification for 'Image360 (~> 0.1.3)'`

**Comment by Ssimboss** [comment]
@ecristerna, this is really strange. Please, send me your Podfile's content.

While you are waiting for solution, you could replace string `pod 'Image360', '~> 0.1.3'` with `pod 'Image360', :git => 'https://github.com/Ssimboss/Image360.git', :tag => ‘0.1.3’`. So, you would be able to install required version of Image360 directly from GitHub.

**Comment by ecristerna** [comment]
@Ssimboss so I had to run `pod repo remove master`, then uninstall and install cocoapods, and the issue seems to be gone.

Thanks for your response!
