### ISSUE TITLE
App doesn't work in release mode 

### ISSUE THREAD

**Issue by kaushaldeo** [Ssimboss/Image360#10]
The app doesn't work in release mode with base SDK 11.2 with Xcode 9.2. It shows the blue screen in the sphere shape. I have tried the example to run in the release. 
![screenshot2](https://user-images.githubusercontent.com/8772461/35709206-67be1a86-0766-11e8-9435-2955041d4851.png)

**Comment by Ssimboss** [comment]
@kaushaldeo, thanks for your notice. I'll take a look on this serious problem.

**Comment by Ssimboss** [comment]
@kaushaldeo Thank you so much for finding this bug! Image360 **1.1.0** contains all needed fixes to make it work in release mode again.

**Comment by kaushaldeo** [comment]
Thanks, @Ssimboss for fixing this issue.
