### ISSUE TITLE
Image shrinks/stretches

### ISSUE THREAD

**Issue by ecristerna** [Ssimboss/Image360#3]
I am using your code with an image with dimensions 2000 × 1000. Is working fine, but seems to shrink or stretch the original image depending on the screen.

Is there any way to prevent this? My guess is the dimension of the sphere may be taking the dimensions of the screen into consideration, instead of those of the image.

This is the original image:

![test](https://cloud.githubusercontent.com/assets/3680271/23221261/3cf03ff4-f8ea-11e6-9dc4-9bf5153a5099.jpg)

This is how it looks on iPhone 6:

<img width="409" alt="screen shot 2017-02-22 at 10 33 15 am" src="https://cloud.githubusercontent.com/assets/3680271/23221318/5f7e31f2-f8ea-11e6-80db-2fd61c39ef48.png">

On iPhone 5:

<img width="406" alt="screen shot 2017-02-22 at 10 32 50 am" src="https://cloud.githubusercontent.com/assets/3680271/23221273/463f8ad8-f8ea-11e6-9c96-96a223c5d9ed.png">

On iPad:

<img width="958" alt="screen shot 2017-02-22 at 10 35 23 am" src="https://cloud.githubusercontent.com/assets/3680271/23221445/bec4cef0-f8ea-11e6-95b6-99373370adda.png">

Thanks,

**Comment by Ssimboss** [comment]
Hi, 
Thank you for a feedback. I'll fix this problem in a few days. 
I hope it's not critical for you at the moment.

**Comment by ecristerna** [comment]
@Ssimboss thanks for the rapid response! It would really improve my app if you could fix this. No rush though.

**Comment by Ssimboss** [comment]
@ecristerna 
I've just updated **Image360** to version 0.1.4. It should solve your problem.
