### ISSUE TITLE
Customize Inertia value

### ISSUE THREAD

**Issue by ecristerna** [Ssimboss/Image360#4]
Hey, is there any way to customize the inertia value? I find the `short` one (1.0) kind of slow, and the `long` (10.0) way too fast.

Thanks,

**Comment by Ssimboss** [comment]
Hi,
At the moment there is no way to customize it. Only with some external controller gesture controller. I'll fix it in next version in a few days.

**Comment by Ssimboss** [comment]
@ecristerna 
Hi,
I'm glad to say that your problem is solved in version 0.1.6
Since this version `Inertia` enum is deprecated. Now `Image360Controller.inertia` is a `Float` with range 0...1.
