### ISSUE TITLE
Rotate with device

### ISSUE THREAD

**Issue by ecristerna** [Ssimboss/Image360#5]
Me again; you have plans on implementing the device rotation feature?

Thanks,

**Comment by Ssimboss** [comment]
Hi,
Do you mean rotation control via gyroscope/accelerometer or device-orientation(portrait/landscape) handling?

Accelerometer control will be implemented till Sunday evening. As for orientation handling, it will be ready only on next week.

**Comment by ecristerna** [comment]
Thanks so much! I meant the gyroscope/accelerometer functionality, so the the image rotates while the user is moving.

**Comment by Ssimboss** [comment]
@ecristerna 
Hi again,
I've implemented this feature in version 0.1.6. Take a look, please.

**Comment by ecristerna** [comment]
hey @Ssimboss 

thanks for the fast response. it is working really nice; only issue I encountered is that when device is in landscape, the motionManager detects the changes as if device was in portrait (moving up/down rotates image left/right and viceversa).

**Comment by Ssimboss** [comment]
@ecristerna,
Thank you for your feedback. As I wrote before, I'll pay attention for orientation handling on next week.

**Comment by Ssimboss** [comment]
@ecristerna, Hi.
I've updated Image360 to version 0.2.1
I'm glad to say that Image360 now is able to handle interface orientation.

**Comment by ecristerna** [comment]
thanks @Ssimboss i'll take a look at it.
