### ISSUE TITLE
Cannot show Image from URL

### ISSUE THREAD

**Issue by coderGo93** [Ssimboss/Image360#6]
Hi, i'm trying to show image 360 from url(internet). I don't know if there is a problem with library.

The error appears::
 fatal error: leftTexture generation failed: file ...Pods/Image360/Image360/Core/Image360View.swift, line 255

I already have image(UIImage with data) downloaded. It can pass Image to 360Controller without problems. I don't know why happens this error.

Is it a bug or behavior intentional?

Sorry for my english

**Comment by Ssimboss** [comment]
Hi,
Please share URL where your image is located.

**Comment by coderGo93** [comment]
Sure.
Is not my image, is from internet I found.

https://d36tnp772eyphs.cloudfront.net/blogs/1/2006/11/360-panorama-matador-seo.jpg

**Comment by Ssimboss** [comment]
@edgars, thank you for your feedback. I'll pay attention for your problem &  fix this bug in next few days.
Hope it's not critical for you at the moment)

**Comment by Ssimboss** [comment]
@edgars93, Hi.
I've tested your URL. Everything sims to be OK. Code example is located here: https://github.com/Ssimboss/Image360/tree/image-from-url

Please, take a look. I'll remove this branch from repository on next week.

**Comment by coderGo93** [comment]
Ok, thanks. 

I found another maybe bug.

I'm trying to make another controller that work as fullscreen(modal).

It seems I cannot use two Image controller(one container view with class Image360Controller per controller).

I mean, the first one It works, it shows. But when a tapped the Container view(Image360), it shows another controller as modal, it passed data with success. But it doesn't show nothing, it's all black. When I dismiss this modal, then the first controller, it shows something and then it's black in the container.

My theory is doesn't work if you have two, the first one it shows, but then later it shows nothing(black in container view)

**Comment by Ssimboss** [comment]
@edgars93, thanks for the feedback. I'll fix this bug in next few days.

**Comment by Ssimboss** [comment]
@edgars93 Hi,

Today I've finally solved this bug. Please, update your version of **Image360** to **0.2.2**.
